name: Deploy Next.js App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Next.js
        # Your build, test, and deploy steps for Next.js go here
        run: echo "Building and deploying Next.js..."
